//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ParcialJP.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PARCIALJPEntities : DbContext
    {
        public PARCIALJPEntities()
            : base("name=PARCIALJPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<MARCA> MARCAs { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual DbSet<MEDICO> Medicos { get; set; }
        public virtual DbSet<PACIENTE> PACIENTEs { get; set; }
        public virtual DbSet<TIPO_FARMACO> TIPO_FARMACO { get; set; }
        public virtual DbSet<UBICACION> UBICACIONs { get; set; }
        public virtual DbSet<VISITA> VISITAs { get; set; }
    }
}
