//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ParcialJP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public int ID_PACIENTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CEDULA { get; set; }
        public Nullable<int> NUM_CARNET { get; set; }
        public string TIPO_PACIENTE { get; set; }
        public string ESTADO { get; set; }
    }
}
