//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ParcialJP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public int ID_MEDICO { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public string TANDA_LABOR { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string ESTADO { get; set; }
    }
}
