//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ParcialJP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public int ID_VISITA { get; set; }
        public string NOMBRE_MEDICO { get; set; }
        public string NOMBRE_PACIENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public string SINTOMAS { get; set; }
        public string MEDICAMENTOS { get; set; }
        public string RECOMENDACIONES { get; set; }
        public string ESTADO { get; set; }
    }
}
